"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
async function run() {
  const read = (name) => fs.readFileSync(path.join(__dirname, "..", "js", name), "utf8");
  const THREE = await import(`data:text/javascript;base64,${Buffer.from(read("vendor/three.core.js")).toString("base64")}`);
  const context = vm.createContext({ window: {}, performance });
  ["config.js", "xr-windows.js"].forEach(name => vm.runInContext(read(name), context));
  const E = context.window.Eredita, scene = new THREE.Scene(), group = new THREE.Group(), board = new THREE.Group(); scene.add(group, board);
  const panels = new Map();
  ["jobs", "info"].forEach((id, index) => { const node = new THREE.Group(); node.position.set(index ? 0.6 : -0.6, 0, -1.4); group.add(node); panels.set(id, { node }); });
  const dashboard = { getPanel: id => panels.get(id) }, manager = E.XRWindows.create({ THREE, dashboard });
  const viewer = { position: new THREE.Vector3(), quaternion: new THREE.Quaternion() };
  const record = (x) => ({ tracked: true, squeezing: false, axes: [0, 0], gripPosition: new THREE.Vector3(x, -0.25, -0.3), gripQuaternion: new THREE.Quaternion(), direction: new THREE.Vector3(0, 0, -1) });
  const left = record(-0.2), right = record(0.2), records = [left, right];
  const hit = id => ({ object: { userData: { xrTarget: { kind: "panel-handle", panelId: id } } } });
  const hits = new Map([[left, hit("jobs")], [right, hit("info")]]);
  const update = (enabled = true) => { scene.updateMatrixWorld(true); manager.update(records, hits, viewer, 1 / 72, enabled); };
  const jobs = panels.get("jobs").node, info = panels.get("info").node;
  const infoStart = info.position.clone(), boardMatrix = board.matrixWorld.clone();
  update(); left.squeezing = true; update(); assert.equal(manager.isDragging(left), true);
  left.gripPosition.x += 0.2; for (let i = 0; i < 30; i++) update();
  assert.ok(jobs.position.x > -0.41); assert.deepEqual(info.position, infoStart);
  assert.deepEqual(board.matrixWorld, boardMatrix, "Déplacer une fenêtre ne transforme jamais le plateau");
  left.gripQuaternion.setFromAxisAngle(new THREE.Vector3(0, 1, 0), 0.25); for (let i = 0; i < 30; i++) update();
  assert.ok(jobs.quaternion.angleTo(new THREE.Quaternion()) > 0.2, "Orientation par le poignet");
  left.axes = [1, 1]; for (let i = 0; i < 30; i++) update();
  assert.ok(jobs.scale.x > 1); left.axes = [0, 0];
  left.squeezing = false; update(); const released = jobs.position.clone(); left.gripPosition.x += 1; update();
  assert.deepEqual(jobs.position, released, "La fenêtre reste stable après relâchement"); assert.equal(jobs.userData.customLayout, true);
  left.squeezing = true; right.squeezing = true; update(); assert.equal(manager.diagnostics.length, 2, "Les mains saisissent deux fenêtres indépendantes");
  left.gripPosition.set(100, 100, 100); for (let i = 0; i < 50; i++) update();
  const horizontal = Math.hypot(jobs.position.x, jobs.position.z);
  assert.ok(horizontal <= E.Config.xr.windowMaxDistance + 0.001); assert.ok(jobs.position.y <= E.Config.xr.windowMaxY + 0.001);
  assert.equal(manager.cancel(), true); assert.deepEqual(jobs.position, released, "B annule la pose en cours");
  left.squeezing = false; right.squeezing = false; update();
  hits.set(left, { object: { userData: { xrTarget: { kind: "dashboard-button", panelId: "jobs" } } } });
  left.squeezing = true; update(); assert.equal(manager.active, false, "Un bouton n'est pas une poignée");
  left.squeezing = false; update(); hits.set(left, hit("jobs")); left.squeezing = true; update(); left.tracked = false; update();
  assert.equal(manager.active, false, "Perdre le suivi libère la saisie");
  left.tracked = true; left.squeezing = false; update(); left.squeezing = true; update(false); assert.equal(manager.active, false, "La manipulation plateau désactive les fenêtres");
  assert.equal(manager.adjust("jobs", "face", viewer), true); assert.equal(manager.adjust("jobs", "near", viewer), true);
  assert.equal(manager.adjust("missing", "near", viewer), false);
  for (let i = 0; i < 100; i++) manager.adjust("jobs", "grow", viewer);
  assert.ok(jobs.userData.windowUserScale <= E.Config.xr.windowMaxScale);
  manager.dispose(); assert.equal(manager.active, false);
  console.log("Fenêtres XR : indépendance plateau, deux mains, rotation, distance/taille, annulation, limites, pertes de suivi et alternative par boutons validées.");
}
run().catch(error => { console.error(error); process.exitCode = 1; });
